In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#Import Libraries
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
#Load the dataset
heart_df=pd.read_csv('/content/drive/MyDrive/Projects/Heart Disease/heart.csv')
heart_df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [ ]:
#Get the summary
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [ ]:
#Get the statistics

In [ ]:
heart_df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [ ]:
heart_df.describe(include='all')

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
count,918.000000,918,918,918.000000,918.000000,918.000000,918,918.000000,918,918.000000,918,918.000000
unique,NaN,2,4,NaN,NaN,NaN,3,NaN,2,NaN,3,NaN
top,NaN,M,ASY,NaN,NaN,NaN,Normal,NaN,N,NaN,Flat,NaN
freq,NaN,725,496,NaN,NaN,NaN,552,NaN,547,NaN,460,NaN
mean,53.510893,NaN,NaN,132.396514,198.799564,0.233115,NaN,136.809368,NaN,0.887364,NaN,0.553377
std,9.432617,NaN,NaN,18.514154,109.384145,0.423046,NaN,25.460334,NaN,1.066570,NaN,0.497414
min,28.000000,NaN,NaN,0.000000,0.000000,0.000000,NaN,60.000000,NaN,-2.600000,NaN,0.000000
25%,47.000000,NaN,NaN,120.000000,173.250000,0.000000,NaN,120.000000,NaN,0.000000,NaN,0.000000
50%,54.000000,NaN,NaN,130.000000,223.000000,0.000000,NaN,138.000000,NaN,0.600000,NaN,1.000000
75%,60.000000,NaN,NaN,140.000000,267.000000,0.000000,NaN,156.000000,NaN,1.500000,NaN,1.000000
max,77.000000,NaN,NaN,200.000000,603.000000,1.000000,NaN,202.000000,NaN,6.200000,NaN,1.000000

Data Preprocessing

In [ ]:
#Check for null values
heart_df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [ ]:
#Check for duplicates
heart_df.duplicated().sum()

np.int64(0)

In [ ]:
#Checking the number of unique values in each feature
heart_df.nunique()

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [ ]:
#View the columns
cat_col = heart_df.select_dtypes(include='object').columns
cat_col

Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object')

Converting categorical variables to numerical

In [ ]:
heart_df['ChestPainType'].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [ ]:
range(heart_df['ChestPainType'].nunique())

range(0, 4)

In [ ]:
#Since there are a lot of categorical values we will use this loop
for col in cat_col:
  print(col)
  print((heart_df[col].unique()),list(range(heart_df[col].nunique())))
  heart_df[col].replace((heart_df[col].unique()),range(heart_df[col].nunique()),inplace=True)
  print('*'*90)
  print()

Sex
['M' 'F'] [0, 1]
******************************************************************************************

ChestPainType
['ATA' 'NAP' 'ASY' 'TA'] [0, 1, 2, 3]
******************************************************************************************

RestingECG
['Normal' 'ST' 'LVH'] [0, 1, 2]
******************************************************************************************

ExerciseAngina
['N' 'Y'] [0, 1]
******************************************************************************************

ST_Slope
['Up' 'Flat' 'Down'] [0, 1, 2]
******************************************************************************************

In [ ]:
heart_df['Cholesterol'].value_counts()

Cholesterol
0      172
254     11
220     10
223     10
204      9
      ...
353      1
278      1
157      1
176      1
131      1
Name: count, Length: 222, dtype: int64

Since cholesterol cannot be 0, we will use KNN imputer

In [ ]:
# Replace all 0 with nan values
heart_df['Cholesterol'].replace(0,np.nan,inplace=True)

In [ ]:
# Replace the nan values with the imputer KNN values
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(heart_df)
heart_df = pd.DataFrame(after_impute,columns=heart_df.columns)

In [ ]:
heart_df['Cholesterol'].isna().sum()

np.int64(0)

In [ ]:
# Check for any 0 values
count = 0
for i in heart_df['Cholesterol']:
  if i == 0:
    count += 1
print(count)

0

Doing the same replacement for Resting Blood Pressure

In [ ]:
heart_df['RestingBP'][heart_df['RestingBP'] == 0]

449    0.0
Name: RestingBP, dtype: float64

In [ ]:
from sklearn.impute import KNNImputer
heart_df['RestingBP'].replace(0,np.nan,inplace=True)
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(heart_df)
heart_df = pd.DataFrame(after_impute,columns=heart_df.columns)

In [ ]:
heart_df['RestingBP'].isnull().sum()

np.int64(0)

Change column type to int

In [ ]:
# Change the type of data type into integer except Oldpeak column
withoutOldPeak = heart_df.columns
withoutOldPeak = withoutOldPeak.drop('Oldpeak')
heart_df[withoutOldPeak] = heart_df[withoutOldPeak].astype('int32')

In [ ]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int32
 1   Sex             918 non-null    int32
 2   ChestPainType   918 non-null    int32
 3   RestingBP       918 non-null    int32
 4   Cholesterol     918 non-null    int32
 5   FastingBS       918 non-null    int32
 6   RestingECG      918 non-null    int32
 7   MaxHR           918 non-null    int32
 8   ExerciseAngina  918 non-null    int32
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    int32
 11  HeartDisease    918 non-null    int32
dtypes: float64(1), int32(11)
memory usage: 46.7 KB

Data Visualization

In [ ]:
import plotly.express as px

In [ ]:
heart_df.sample()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
581,48,0,2,140,208,0,0,159,1,1.5,0,1

In [ ]:
# Get the correlation between target and attributes
heart_df.corr()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
Age,1.000000,-0.055750,0.214164,0.263128,0.057108,0.198039,0.213152,-0.382045,0.215793,0.258612,0.268264,0.282039
Sex,-0.055750,1.000000,-0.179766,-0.009658,0.080395,-0.120076,0.018343,0.189186,-0.190664,-0.105734,-0.150693,-0.305445
ChestPainType,0.214164,-0.179766,1.000000,0.073016,0.038855,0.155111,0.112067,-0.273076,0.324049,0.300846,0.352364,0.459017
RestingBP,0.263128,-0.009658,0.073016,1.000000,0.113194,0.067556,0.094144,-0.109329,0.152621,0.174464,0.082401,0.118333
Cholesterol,0.057108,0.080395,0.038855,0.113194,1.000000,0.058798,0.074925,-0.028855,0.083761,0.065988,0.071345,0.101263
FastingBS,0.198039,-0.120076,0.155111,0.067556,0.058798,1.000000,0.050707,-0.131438,0.060451,0.052698,0.175774,0.267291
RestingECG,0.213152,0.018343,0.112067,0.094144,0.074925,0.050707,1.000000,0.048552,0.036119,0.114428,0.078807,0.061011
MaxHR,-0.382045,0.189186,-0.273076,-0.109329,-0.028855,-0.131438,0.048552,1.000000,-0.370425,-0.160691,-0.343419,-0.400421
ExerciseAngina,0.215793,-0.190664,0.324049,0.152621,0.083761,0.060451,0.036119,-0.370425,1.000000,0.408752,0.428706,0.494282
Oldpeak,0.258612,-0.105734,0.300846,0.174464,0.065988,0.052698,0.114428,-0.160691,0.408752,1.000000,0.501921,0.403951
ST_Slope,0.268264,-0.150693,0.352364,0.082401,0.071345,0.175774,0.078807,-0.343419,0.428706,0.501921,1.000000,0.558771
HeartDisease,0.282039,-0.305445,0.459017,0.118333,0.101263,0.267291,0.061011,-0.400421,0.494282,0.403951,0.558771,1.000000

In [ ]:
# Checking the correlation with heart disease
heart_df.corr()['HeartDisease']

Age               0.282039
Sex              -0.305445
ChestPainType     0.459017
RestingBP         0.118333
Cholesterol       0.101263
FastingBS         0.267291
RestingECG        0.061011
MaxHR            -0.400421
ExerciseAngina    0.494282
Oldpeak           0.403951
ST_Slope          0.558771
HeartDisease      1.000000
Name: HeartDisease, dtype: float64

In [ ]:
# Slicing the Heartdisease column
heart_df.corr()['HeartDisease'][:-1]

Age               0.282039
Sex              -0.305445
ChestPainType     0.459017
RestingBP         0.118333
Cholesterol       0.101263
FastingBS         0.267291
RestingECG        0.061011
MaxHR            -0.400421
ExerciseAngina    0.494282
Oldpeak           0.403951
ST_Slope          0.558771
Name: HeartDisease, dtype: float64

In [ ]:
# Sorting and plotting the correlation
px.line(heart_df.corr()['HeartDisease'][:-1].sort_values())

Age and Heart Disease distribution

In [ ]:
# Using sunburst plot
px.sunburst(heart_df,path=['HeartDisease','Age'])

In [ ]:
px.histogram(heart_df,x='Age',color='HeartDisease')

Percentage of Heart Disease data distribution

In [ ]:
# Percentage of data distribution
px.pie(heart_df,names='HeartDisease',title='Percentage of Heart disease')

Chest Pain Type vs Heart Disease Plot

In [ ]:
px.histogram(heart_df,x='ChestPainType',color='HeartDisease',title='Chest Pain Type vs Heart Disease')

RestingBP vs HeartDisease

In [ ]:
heart_df['RestingBP'].unique()

array([140, 160, 130, 138, 150, 120, 110, 136, 115, 100, 124, 113, 125,
       145, 112, 132, 118, 170, 142, 190, 135, 180, 108, 155, 128, 106,
        92, 200, 122,  98, 105, 133,  95,  80, 137, 185, 165, 126, 152,
       116, 144, 154, 134, 104, 139, 131, 141, 178, 146, 158, 123, 102,
        96, 143, 172, 156, 114, 127, 101, 174,  94, 148, 117, 192, 129,
       164], dtype=int32)

In [ ]:
px.sunburst(heart_df,path=['HeartDisease','RestingBP'])

In [ ]:
# Violin plot for MaxHR vs Heart Disease
px.violin(heart_df,x='HeartDisease',y='MaxHR',color='HeartDisease')

Old Peak vs Heart Disease

In [ ]:
# Violin plot
px.violin(heart_df,x='HeartDisease',y='Oldpeak',color='HeartDisease')

ST Slope vs Heart Disease

In [ ]:
# For 3 categorical features we use histogram
px.histogram(heart_df,x='ST_Slope',color='HeartDisease')

Exercise Angina vs Heart Disease

In [ ]:
px.histogram(heart_df,x='ExerciseAngina',color='HeartDisease')

Machine Learning

In [ ]:
# Test Train split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
    heart_df.drop('HeartDisease',axis=1),
    heart_df['HeartDisease'],
    test_size = 0.2,
    random_state = 42,
    stratify = heart_df['HeartDisease']
)

Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

solver = ['lbfgs','liblinear','newton-cg','newton-cholesky','sag','saga']
best_solver = ''
test_score = np.zeros(6)
for i, n in enumerate(solver):
  lr = LogisticRegression(solver = n).fit(X_train,y_train)
  test_score[i] = lr.score(X_test,y_test)
  if lr.score(X_test,y_test) == test_score.max():
    best_solver = n

print(best_solver)
lr = LogisticRegression(solver = best_solver)
lr.fit(X_train,y_train)
lr_pred = lr.predict(X_test)
print(f'LogisticRegression Score : {accuracy_score(y_test,lr_pred)}')

newton-cholesky
LogisticRegression Score : 0.8586956521739131

Support Vector Machine

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import f1_score

kernels = {'linear':0,'poly':0,'rbf':0,'sigmoid':0}
best = ''
for i in kernels:
  svm = SVC(kernel = i)
  svm.fit(X_train,y_train)
  yhat = svm.predict(X_test)
  kernels[i] = f1_score(y_test,yhat,average='weighted')
  if kernels[i] == max(kernels.values()):
    best = i

svm = SVC(kernel = best)
svm.fit(X_train,y_train)
svm_pred = svm.predict(X_test)
print(f'SVM f1_score kernel({best}): {f1_score(y_test, svm_pred, average='weighted')}')

SVM f1_score kernel(linear): 0.8422922535440344

Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

dtree = DecisionTreeClassifier(class_weight = 'balanced')
param_grid = {
    'max_depth' : [3,4,5,6,7,8],
    'min_samples_split' : [2,3,4],
    'min_samples_leaf' : [1,2,3,4],
    'random_state' : [0,42]
}

grid_search = GridSearchCV(dtree, param_grid, cv = 5)
grid_search.fit(X_train,y_train)
Ctree = DecisionTreeClassifier(**grid_search.best_params_,class_weight='balanced')
Ctree.fit(X_train,y_train)
dtc_pred = Ctree.predict(X_test)
print('Decision Tree Accuracy :', accuracy_score(y_test,dtc_pred))

Decision Tree Accuracy : 0.8097826086956522

Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

rfc = RandomForestClassifier()
param_grid ={
    'n_estimators':[50,100,150,500],
    'max_features':['sqrt','log2',None],
    'max_depth':[3,6,9,19],
    'max_leaf_nodes':[3,6,9]
}

grid_search = GridSearchCV(rfc,param_grid)
grid_search.fit(X_train,y_train)
rfctree = RandomForestClassifier(**grid_search.best_params_)
rfctree.fit(X_train,y_train)
rfc_pred = rfctree.predict(X_test)
print('Random Forest Classifier Accuracy : ',accuracy_score(y_test,rfc_pred))

Random Forest Classifier Accuracy :  0.8369565217391305

In [ ]:
import pickle
file = open('LogisticRegression.pkl','wb')
pickle.dump(lr,file)

In [ ]:
import pickle
file = open('SVM.pkl','wb')
pickle.dump(svm,file)

In [ ]:
import pickle
file = open('tree.pkl','wb')
pickle.dump(Ctree,file)

In [ ]:
import pickle
file = open('RandomForest.pkl','wb')
pickle.dump(rfctree,file)